name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: use setup nodejs
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: 14.15.0
        
      - name: Run a one-line script
        run: echo Hello, world!

      - name: install dependency
        run: 
          npm ci
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: actions/checkout@v2
      - name: docker image build
        run: docker build -t jeonju .
    
      - name: upload to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: yeoul/jeonju
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
